# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/davydotcom/projects/C++/radi8c2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/davydotcom/projects/C++/radi8c2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/opt/homebrew/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/opt/homebrew/bin/cpack --config ./CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/davydotcom/projects/C++/radi8c2/CMakeFiles /Users/davydotcom/projects/C++/radi8c2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/davydotcom/projects/C++/radi8c2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named radi8c2

# Build rule for target.
radi8c2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 radi8c2
.PHONY : radi8c2

# fast build rule for target.
radi8c2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radi8c2.dir/build.make CMakeFiles/radi8c2.dir/build
.PHONY : radi8c2/fast

#=============================================================================
# Target rules for targets named screen

# Build rule for target.
screen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 screen
.PHONY : screen

# fast build rule for target.
screen/fast:
	$(MAKE) $(MAKESILENT) -f external/FTXUI/CMakeFiles/screen.dir/build.make external/FTXUI/CMakeFiles/screen.dir/build
.PHONY : screen/fast

#=============================================================================
# Target rules for targets named dom

# Build rule for target.
dom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dom
.PHONY : dom

# fast build rule for target.
dom/fast:
	$(MAKE) $(MAKESILENT) -f external/FTXUI/CMakeFiles/dom.dir/build.make external/FTXUI/CMakeFiles/dom.dir/build
.PHONY : dom/fast

#=============================================================================
# Target rules for targets named component

# Build rule for target.
component: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 component
.PHONY : component

# fast build rule for target.
component/fast:
	$(MAKE) $(MAKESILENT) -f external/FTXUI/CMakeFiles/component.dir/build.make external/FTXUI/CMakeFiles/component.dir/build
.PHONY : component/fast

src/Connection.o: src/Connection.cpp.o
.PHONY : src/Connection.o

# target to build an object file
src/Connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radi8c2.dir/build.make CMakeFiles/radi8c2.dir/src/Connection.cpp.o
.PHONY : src/Connection.cpp.o

src/Connection.i: src/Connection.cpp.i
.PHONY : src/Connection.i

# target to preprocess a source file
src/Connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radi8c2.dir/build.make CMakeFiles/radi8c2.dir/src/Connection.cpp.i
.PHONY : src/Connection.cpp.i

src/Connection.s: src/Connection.cpp.s
.PHONY : src/Connection.s

# target to generate assembly for a file
src/Connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radi8c2.dir/build.make CMakeFiles/radi8c2.dir/src/Connection.cpp.s
.PHONY : src/Connection.cpp.s

src/FileTransfer.o: src/FileTransfer.cpp.o
.PHONY : src/FileTransfer.o

# target to build an object file
src/FileTransfer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radi8c2.dir/build.make CMakeFiles/radi8c2.dir/src/FileTransfer.cpp.o
.PHONY : src/FileTransfer.cpp.o

src/FileTransfer.i: src/FileTransfer.cpp.i
.PHONY : src/FileTransfer.i

# target to preprocess a source file
src/FileTransfer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radi8c2.dir/build.make CMakeFiles/radi8c2.dir/src/FileTransfer.cpp.i
.PHONY : src/FileTransfer.cpp.i

src/FileTransfer.s: src/FileTransfer.cpp.s
.PHONY : src/FileTransfer.s

# target to generate assembly for a file
src/FileTransfer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radi8c2.dir/build.make CMakeFiles/radi8c2.dir/src/FileTransfer.cpp.s
.PHONY : src/FileTransfer.cpp.s

src/Protocol.o: src/Protocol.cpp.o
.PHONY : src/Protocol.o

# target to build an object file
src/Protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radi8c2.dir/build.make CMakeFiles/radi8c2.dir/src/Protocol.cpp.o
.PHONY : src/Protocol.cpp.o

src/Protocol.i: src/Protocol.cpp.i
.PHONY : src/Protocol.i

# target to preprocess a source file
src/Protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radi8c2.dir/build.make CMakeFiles/radi8c2.dir/src/Protocol.cpp.i
.PHONY : src/Protocol.cpp.i

src/Protocol.s: src/Protocol.cpp.s
.PHONY : src/Protocol.s

# target to generate assembly for a file
src/Protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radi8c2.dir/build.make CMakeFiles/radi8c2.dir/src/Protocol.cpp.s
.PHONY : src/Protocol.cpp.s

src/TUI.o: src/TUI.cpp.o
.PHONY : src/TUI.o

# target to build an object file
src/TUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radi8c2.dir/build.make CMakeFiles/radi8c2.dir/src/TUI.cpp.o
.PHONY : src/TUI.cpp.o

src/TUI.i: src/TUI.cpp.i
.PHONY : src/TUI.i

# target to preprocess a source file
src/TUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radi8c2.dir/build.make CMakeFiles/radi8c2.dir/src/TUI.cpp.i
.PHONY : src/TUI.cpp.i

src/TUI.s: src/TUI.cpp.s
.PHONY : src/TUI.s

# target to generate assembly for a file
src/TUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radi8c2.dir/build.make CMakeFiles/radi8c2.dir/src/TUI.cpp.s
.PHONY : src/TUI.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radi8c2.dir/build.make CMakeFiles/radi8c2.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radi8c2.dir/build.make CMakeFiles/radi8c2.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/radi8c2.dir/build.make CMakeFiles/radi8c2.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... component"
	@echo "... dom"
	@echo "... radi8c2"
	@echo "... screen"
	@echo "... src/Connection.o"
	@echo "... src/Connection.i"
	@echo "... src/Connection.s"
	@echo "... src/FileTransfer.o"
	@echo "... src/FileTransfer.i"
	@echo "... src/FileTransfer.s"
	@echo "... src/Protocol.o"
	@echo "... src/Protocol.i"
	@echo "... src/Protocol.s"
	@echo "... src/TUI.o"
	@echo "... src/TUI.i"
	@echo "... src/TUI.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

